### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Cvar1984** [orangetw/tsh#1]
tsh.c:184:24: warning: implicit declaration of function 'getpass' is invalid in C99
      [-Wimplicit-function-declaration]
            password = getpass( "Password: " );
                       ^
tsh.c:184:22: warning: incompatible integer to pointer conversion assigning to 'char *'
      from 'int' [-Wint-conversion]
            password = getpass( "Password: " );
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.

**Comment by orangetw** [comment]
It seems to be warnings, not errors. It that important?
